### ISSUE TITLE
The implementation of /api/stream has serious performance issues

### ISSUE THREAD

**Issue by reorx** [rishi-raj-jain/upstash-nextjs-publish-messages-with-sse-example#1]
I discovered this repository through [this article](https://upstash.com/blog/realtime-notifications), as I admire the work of the @upstash team and wanted to learn more about them.

Upon examining the code, I noticed that the implementation of /api/stream has serious performance issues.

Initially, a Redis instance is globally initialized: `const redisSubscriber = new Redis(process.env.UPSTASH_REDIS_URL)`

However, within the request handler, you invoke `Redis.on`, which means that a new listener is registered on the same global Redis instance for every request made.

The consequence of this approach is that after the Nth request, a published message will trigger the message listener N times. This will gradually slow down the server and could eventually result in a memory leak.

The proper method would be to initialize a new Redis instance for each request and close the connection (`Redis.quit`) once the event stream controller is aborted from the client side.

In future, when writing marketing blogs, please be meticulous and mindful, to prevent the dissemination of misleading information. As spreading incorrect information can ultimately result in losing trust from people.

**Comment by rishi-raj-jain** [comment]
> However, within the request handler, you invoke Redis.on, which means that a new listener is registered on the same global Redis instance for every request made.

Is that the case with serverless?

**Comment by rishi-raj-jain** [comment]
> The proper method would be to initialize a new Redis instance for each request and close the connection (Redis.quit) once the event stream controller is aborted from the client side.

I agree, and that's exactly what happens in serverless setup according to me.

**Comment by rishi-raj-jain** [comment]
It seems you're thinking in the form of a server-first setup, but the whole setup is deployed to Vercel defaulting to serverless.

Open to learning and improve.
